[package]
name = "mvlc-render"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[lib]
name = "mvlc_render"

[dependencies]
mvlc-core.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
ash.workspace = true
vk-mem.workspace = true
winit.workspace = true
ash-window = "0.13"

[build-dependencies]
bindgen.workspace = true
