[package]
name = "mvlc-render"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[lib]
name = "mvlc_render"

[dependencies]
mvlc-core.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
ash.workspace = true
vk-mem.workspace = true
winit.workspace = true
ash-window = "0.12"
raw-window-handle = "0.5"

# Color management and processing (optional)
# libplacebo = "0.7"
# libplacebo-sys = "0.7"

[build-dependencies]
bindgen.workspace = true
